
import { Language, LanguageCode, Translations } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'hr', name: 'Hrvatski', flag: '🇭🇷' },
];

export const AGE_GROUPS = [2, 3, 4, 5, 6, 7];

export const GARDEN_COLORS = [
  { name: 'Petal Pink', value: '#fff5f7' },
  { name: 'Sky Blue', value: '#f0f9ff' },
  { name: 'Mint Leaf', value: '#f0fdf4' },
  { name: 'Lavender', value: '#f5f3ff' },
  { name: 'Sunny Day', value: '#fffbeb' },
  { name: 'Cloud White', value: '#ffffff' },
  { name: 'Apricot', value: '#fff7ed' },
];

export const UI_TRANSLATIONS: Translations = {
  welcome: {
    en: 'Welcome to StoryTime!',
    de: 'Willkommen bei StoryTime!',
    fr: 'Bienvenue chez StoryTime !',
    es: '¡Bienvenido a StoryTime!',
    it: 'Benvenuti a StoryTime!',
    pt: 'Bem-vindo ao StoryTime!',
    nl: 'Welkom bij StoryTime!',
    pl: 'Witamy w StoryTime!',
    ru: 'Добро пожаловать в StoryTime!',
    sv: 'Välkommen till StoryTime!',
    hr: 'Dobrodošli u StoryTime!',
  },
  selectLanguage: {
    en: 'Pick your language',
    de: 'Wähle deine Sprache',
    fr: 'Choisissez votre langue',
    es: 'Elige tu idioma',
    it: 'Scegli la tua lingua',
    pt: 'Escolha o seu idioma',
    nl: 'Kies je taal',
    pl: 'Wybierz swój język',
    ru: 'Выберите ваш язык',
    sv: 'Välj ditt språk',
    hr: 'Odaberite svoj jezik',
  },
  tapToStart: {
    en: 'Tap below to start your adventure!',
    de: 'Tippe unten, um dein Abenteuer zu beginnen!',
    fr: 'Appuyez ci-dessous pour commencer votre aventure !',
    es: '¡Toca abajo para comenzar tu aventura!',
    it: 'Tocca qui sotto per iniziare la tua avventura!',
    pt: 'Toque abaixo para começar sua aventura!',
    nl: 'Tik hieronder om je avontuur te beginnen!',
    pl: 'Stuknij poniżej, aby rozpocząć przygodę!',
    ru: 'Нажмите внизу, чтобы начать приключение!',
    sv: 'Tryck nedan för att börja ditt äventyr!',
    hr: 'Dodirnite dolje da započnete svoju avanturu!',
  },
  enterGarden: {
    en: 'Enter Garden',
    de: 'Garten betreten',
    fr: 'Entrer dans le jardin',
    es: 'Entrar al jardín',
    it: 'Entra nel giardino',
    pt: 'Entrar no jardim',
    nl: 'Tuin betreden',
    pl: 'Wejdź do ogrodu',
    ru: 'Войти в сад',
    sv: 'Gå in i trädgården',
    hr: 'Uđi u vrt',
  },
  forGardenKeepers: {
    en: 'For Garden Keepers',
    de: 'Für Gärtner',
    fr: 'Pour les jardiniers',
    es: 'Para jardineros',
    it: 'Per i giardinieri',
    pt: 'Para jardineiros',
    nl: 'Voor tuiniers',
    pl: 'Dla ogrodników',
    ru: 'Для садовников',
    sv: 'För trädgårdsmästare',
    hr: 'Za vrtlare',
  },
  gardenKeeper: {
    en: 'Garden Keeper',
    de: 'Gärtner',
    fr: 'Jardinier',
    es: 'Jardinero',
    it: 'Giardiniere',
    pt: 'Jardineiro',
    nl: 'Tuinier',
    pl: 'Ogrodnik',
    ru: 'Садовник',
    sv: 'Trädgårdsmästare',
    hr: 'Vrtlar',
  },
  secretPassword: {
    en: 'Enter the secret password',
    de: 'Gib das geheime Passwort ein',
    fr: 'Entrez le mot de passe secret',
    es: 'Ingresa la contraseña secreta',
    it: 'Inserisci la password segreta',
    pt: 'Digite a senha secreta',
    nl: 'Voer het geheime wachtwoord in',
    pl: 'Wprowadź tajne hasło',
    ru: 'Введите секретный пароль',
    sv: 'Ange det hemliga lösenordet',
    hr: 'Unesite tajnu lozinku',
  },
  wrongPassword: {
    en: 'Wrong password!',
    de: 'Falsches Passwort!',
    fr: 'Mot de passe incorrect !',
    es: '¡Contraseña incorrecta!',
    it: 'Password errata!',
    pt: 'Senha errada!',
    nl: 'Verkeerd wachtwoord!',
    pl: 'Złe hasło!',
    ru: 'Неверный пароль!',
    sv: 'Fel lösenord!',
    hr: 'Pogrešna lozinka!',
  },
  libraryTitle: {
    en: 'My Bookshelf',
    de: 'Mein Bücherregal',
    fr: 'Mon étagère',
    es: 'Mi estantería',
    it: 'La mia libreria',
    pt: 'Minha estante',
    nl: 'Mijn Boekenplank',
    pl: 'Moja półka',
    ru: 'Моя книжная полка',
    sv: 'Min bokhylla',
    hr: 'Moja polica',
  },
  createBook: {
    en: 'Create a Book',
    de: 'Buch erstellen',
    fr: 'Créer un livre',
    es: 'Crear un libro',
    it: 'Crea un libro',
    pt: 'Criar um livro',
    nl: 'Maak een boek',
    pl: 'Stwórz książkę',
    ru: 'Создать книгу',
    sv: 'Skapa en bok',
    hr: 'Izradi knjigu',
  },
  back: {
    en: 'Back', de: 'Zurück', fr: 'Retour', es: 'Atrás', it: 'Indietro', pt: 'Voltar', nl: 'Terug', pl: 'Wstecz', ru: 'Назад', sv: 'Tillbaka', hr: 'Natrag'
  },
  next: {
    en: 'Next', de: 'Weiter', fr: 'Suivant', es: 'Siguiente', it: 'Avanti', pt: 'Próximo', nl: 'Volgende', pl: 'Dalej', ru: 'Далее', sv: 'Nästa', hr: 'Sljedeće'
  },
  finish: {
    en: 'Finish', de: 'Fertig', fr: 'Terminer', es: 'Terminar', it: 'Fine', pt: 'Finalizar', nl: 'Klaar', pl: 'Zakończ', ru: 'Завершить', sv: 'Färdig', hr: 'Završi'
  },
  allAges: {
    en: 'All Ages', de: 'Alle Alter', fr: 'Tous les âges', es: 'Todas las edades', it: 'Tutte le età', pt: 'Todas as idades', nl: 'Alle leeftijden', pl: 'Wszystkie wieki', ru: 'Все возраста', sv: 'Alla åldrar', hr: 'Sve dobne skupine'
  },
  yearsOld: {
    en: 'years old', de: 'Jahre alt', fr: 'ans', es: 'años', it: 'anni', pt: 'anos', nl: 'jaar oud', pl: 'lat', ru: 'лет', sv: 'år', hr: 'godina'
  },
  titlePrompt: {
    en: 'Book Title', de: 'Buchtitel', fr: 'Titre du livre', es: 'Título del libro', it: 'Titolo del libro', pt: 'Título do livro', nl: 'Boektitel', pl: 'Tytuł książki', ru: 'Название книги', sv: 'Boktitel', hr: 'Naslov knjige'
  },
  addPage: {
    en: 'Add Page', de: 'Seite hinzufügen', fr: 'Ajouter une page', es: 'Añadir página', it: 'Aggiungi pagina', pt: 'Adicionar página', nl: 'Pagina toevoegen', pl: 'Dodaj stronę', ru: 'Добавить страницу', sv: 'Lägg till sida', hr: 'Dodaj stranicu'
  },
  pageText: {
    en: 'Page story text...', de: 'Geschichtstext...', fr: 'Texte de l\'histoire...', es: 'Texto de la historia...', it: 'Testo della storia...', pt: 'Texto da história...', nl: 'Verhaaltekst...', pl: 'Tekst strony...', ru: 'Текст страницы...', sv: 'Berättelsetext...', hr: 'Tekst priče...'
  },
  selectImage: {
    en: 'Choose Photo', de: 'Foto wählen', fr: 'Choisir une photo', es: 'Elegir foto', it: 'Scegli foto', pt: 'Escolher foto', nl: 'Foto kiezen', pl: 'Wybierz zdjęcie', ru: 'Выбрать фото', sv: 'Välj foto', hr: 'Odaberi sliku'
  },
  publishLocal: {
    en: 'Publish Locally', de: 'Lokal veröffentlichen', fr: 'Publier localement', es: 'Publicar localmente', it: 'Pubblica in locale', pt: 'Publicar localmente', nl: 'Lokaal publiceren', pl: 'Opublikuj lokalnie', ru: 'Опубликовать локально', sv: 'Publicera lokalt', hr: 'Objavi lokalno'
  },
  publishUniversal: {
    en: 'Publish Universally', de: 'Universell veröffentlichen', fr: 'Publier universellement', es: 'Publicar universalmente', it: 'Pubblica universale', pt: 'Publicar universalmente', nl: 'Universeel publiceren', pl: 'Opublikuj uniwersalnie', ru: 'Опубликовать универсально', sv: 'Publicera universellt', hr: 'Objavi univerzalno'
  },
  sortByRating: {
    en: 'Sort by Rating', de: 'Nach Bewertung sortieren', fr: 'Trier par note', es: 'Ordenar por calificación', it: 'Ordina per valutazione', pt: 'Ordenar por classificação', nl: 'Sorteren op beoordeling', pl: 'Sortuj według oceny', ru: 'Сортировать по рейтингу', sv: 'Sortera efter betyg', hr: 'Sortiraj po ocjeni'
  },
  changeLanguage: {
    en: 'Change Language',
    de: 'Sprache ändern',
    fr: 'Changer de langue',
    es: 'Cambiar idioma',
    it: 'Cambia lingua',
    pt: 'Mudar idioma',
    nl: 'Taal wijzigen',
    pl: 'Zmień język',
    ru: 'Изменить язык',
    sv: 'Ändra språk',
    hr: 'Promijeni jezik',
  },
  saveBook: {
    en: 'Save Book',
    de: 'Buch speichern',
    fr: 'Enregistrer le livre',
    es: 'Guardar libro',
    it: 'Salva libro',
    pt: 'Salvar livro',
    nl: 'Boek opslaan',
    pl: 'Zapisz książkę',
    ru: 'Сохранить книгу',
    sv: 'Spara bok',
    hr: 'Spremi knjigu',
  },
  cancel: {
    en: 'Cancel',
    de: 'Abbrechen',
    fr: 'Annuler',
    es: 'Cancelar',
    it: 'Annulla',
    pt: 'Cancelar',
    nl: 'Annuleren',
    pl: 'Anuluj',
    ru: 'Отмена',
    sv: 'Avbryt',
    hr: 'Odustani',
  },
  logout: {
    en: 'Logout',
    de: 'Abmelden',
    fr: 'Déconnexion',
    es: 'Cerrar sesión',
    it: 'Disconnetti',
    pt: 'Sair',
    nl: 'Uitloggen',
    pl: 'Wyloguj',
    ru: 'Выйти',
    sv: 'Logga ut',
    hr: 'Odjava',
  },
  pageOf: {
    en: 'Page',
    de: 'Seite',
    fr: 'Page',
    es: 'Página',
    it: 'Pagina',
    pt: 'Página',
    nl: 'Pagina',
    pl: 'Strona',
    ru: 'Страница',
    sv: 'Sida',
    hr: 'Stranica',
  },
  noBooksYet: {
    en: 'No books yet',
    de: 'Noch keine Bücher',
    fr: 'Pas encore de livres',
    es: 'Aún no hay libros',
    it: 'Ancora nessun libro',
    pt: 'Ainda não há livros',
    nl: 'Nog geen boeken',
    pl: 'Jeszcze nie ma książek',
    ru: 'Пока нет книг',
    sv: 'Inga böcker ännu',
    hr: 'Još nema knjiga',
  },
  createFirstBook: {
    en: 'Create your first story!',
    de: 'Erstelle deine erste Geschichte!',
    fr: 'Créez votre première histoire !',
    es: '¡Crea tu primera historia!',
    it: 'Crea la tua prima storia!',
    pt: 'Crie sua primeira história!',
    nl: 'Maak je eerste verhaal!',
    pl: 'Stwórz swoją pierwszą historię!',
    ru: 'Создайте свою первую историю!',
    sv: 'Skapa din första berättelse!',
    hr: 'Stvori svoju prvu priču!',
  },
  syncing: {
    en: 'Syncing with the Cloud Garden...',
    de: 'Synchronisiere mit dem Cloud-Garten...',
    fr: 'Synchronisation avec le jardin cloud...',
    es: 'Sincronizando con el jardín de la nube...',
    it: 'Sincronizzazione con il giardino cloud...',
    pt: 'Sincronizando com o jardim em nuvem...',
    nl: 'Synchroniseren met de cloud-tuin...',
    pl: 'Synchronizacja z chmurowym ogrodem...',
    ru: 'Синхронизация с облачным садом...',
    sv: 'Synkroniserar med molnträdgården...',
    hr: 'Sinkronizacija s oblakovnim vrtom...',
  },
  translating: {
    en: 'Magical forces are translating stories...',
    de: 'Magische Kräfte übersetzen Geschichten...',
    fr: 'Des forces magiques traduisent des histoires...',
    es: 'Fuerzas mágicas están traduciendo historias...',
    it: 'Forze magiche stanno traducendo storie...',
    pt: 'Forças mágicas estão traduzindo histórias...',
    nl: 'Magische krachten vertalen verhalen...',
    pl: 'Magiczne siły tłumaczą historie...',
    ru: 'Магические силы переводят истории...',
    sv: 'Magiska krafter översätter berättelser...',
    hr: 'Čarobne sile prevode priče...',
  },
  saving: {
    en: 'Saving to the Cloud Garden...',
    de: 'Speichere im Cloud-Garten...',
    fr: 'Enregistrement dans le jardin cloud...',
    es: 'Guardando en el jardín de la nube...',
    it: 'Salvataggio nel giardino cloud...',
    pt: 'Salvando no jardim em nuvem...',
    nl: 'Opslaan in de cloud-tuin...',
    pl: 'Zapisywanie do chmurowego ogrodu...',
    ru: 'Сохранение в облачный сад...',
    sv: 'Sparar till molnträdgården...',
    hr: 'Spremanje u oblakovni vrt...',
  },
  storageError: {
    en: 'Storage error! Could not save your story.',
    de: 'Speicherfehler! Geschichte konnte nicht gespeichert werden.',
    fr: 'Erreur de stockage ! Impossible d\'enregistrer votre histoire.',
    es: '¡Error de almacenamiento! No se pudo guardar tu historia.',
    it: 'Errore di archiviazione! Impossibile salvare la storia.',
    pt: 'Erro de armazenamento! Não foi possível salvar sua história.',
    nl: 'Opslagfout! Kon je verhaal niet opslaan.',
    pl: 'Błąd przechowywania! Nie można zapisać historii.',
    ru: 'Ошибка хранения! Не удалось сохранить историю.',
    sv: 'Lagringsfel! Kunde inte spara din berättelse.',
    hr: 'Greška pohrane! Nije moguće spremiti priču.',
  },
  author: {
    en: 'Author',
    de: 'Autor',
    fr: 'Auteur',
    es: 'Autor',
    it: 'Autore',
    pt: 'Autor',
    nl: 'Auteur',
    pl: 'Autor',
    ru: 'Автор',
    sv: 'Författare',
    hr: 'Autor',
  },
  byAuthor: {
    en: 'by',
    de: 'von',
    fr: 'par',
    es: 'por',
    it: 'di',
    pt: 'por',
    nl: 'van',
    pl: 'przez',
    ru: 'по',
    sv: 'av',
    hr: 'od',
  },
  ageGroup: {
    en: 'Age',
    de: 'Alter',
    fr: 'Âge',
    es: 'Edad',
    it: 'Età',
    pt: 'Idade',
    nl: 'Leeftijd',
    pl: 'Wiek',
    ru: 'Возраст',
    sv: 'Ålder',
    hr: 'Dob',
  },
  edit: {
    en: 'Edit',
    de: 'Bearbeiten',
    fr: 'Modifier',
    es: 'Editar',
    it: 'Modifica',
    pt: 'Editar',
    nl: 'Bewerken',
    pl: 'Edytuj',
    ru: 'Редактировать',
    sv: 'Redigera',
    hr: 'Uredi',
  },
  delete: {
    en: 'Delete',
    de: 'Löschen',
    fr: 'Supprimer',
    es: 'Eliminar',
    it: 'Elimina',
    pt: 'Excluir',
    nl: 'Verwijderen',
    pl: 'Usuń',
    ru: 'Удалить',
    sv: 'Ta bort',
    hr: 'Izbriši',
  },
  approve: {
    en: 'Approve',
    de: 'Genehmigen',
    fr: 'Approuver',
    es: 'Aprobar',
    it: 'Approva',
    pt: 'Aprovar',
    nl: 'Goedkeuren',
    pl: 'Zatwierdź',
    ru: 'Одобрить',
    sv: 'Godkänn',
    hr: 'Odobri',
  },
  ratedByYou: {
    en: 'Your rating',
    de: 'Deine Bewertung',
    fr: 'Votre note',
    es: 'Tu calificación',
    it: 'La tua valutazione',
    pt: 'Sua classificação',
    nl: 'Jouw beoordeling',
    pl: 'Twoja ocena',
    ru: 'Ваша оценка',
    sv: 'Din bedömning',
    hr: 'Vaša ocjena',
  },
  communityRating: {
    en: 'Community rating',
    de: 'Gemeinschaftsbewertung',
    fr: 'Note de la communauté',
    es: 'Calificación de la comunidad',
    it: 'Valutazione della comunità',
    pt: 'Classificação da comunidade',
    nl: 'Community-beoordeling',
    pl: 'Ocena społeczności',
    ru: 'Оценка сообщества',
    sv: 'Gemenskapsbedömning',
    hr: 'Ocjena zajednice',
  },
  enterPassword: {
    en: 'Secret password...',
    de: 'Geheimes Passwort...',
    fr: 'Mot de passe secret...',
    es: 'Contraseña secreta...',
    it: 'Password segreta...',
    pt: 'Senha secreta...',
    nl: 'Geheim wachtwoord...',
    pl: 'Tajne hasło...',
    ru: 'Секретный пароль...',
    sv: 'Hemligt lösenord...',
    hr: 'Tajna lozinka...',
  },
  enter: {
    en: 'Enter',
    de: 'Eingabe',
    fr: 'Entrer',
    es: 'Entrar',
    it: 'Entra',
    pt: 'Entrar',
    nl: 'Invoeren',
    pl: 'Wpisz',
    ru: 'Войти',
    sv: 'Ange',
    hr: 'Unesi',
  },
  newest: {
    en: 'Newest',
    de: 'Neueste',
    fr: 'Plus récents',
    es: 'Más recientes',
    it: 'Più recenti',
    pt: 'Mais recentes',
    nl: 'Nieuwste',
    pl: 'Najnowsze',
    ru: 'Новейшие',
    sv: 'Nyaste',
    hr: 'Najnovije',
  },
  approved: {
    en: 'Approved',
    de: 'Genehmigt',
    fr: 'Approuvé',
    es: 'Aprobado',
    it: 'Approvato',
    pt: 'Aprovado',
    nl: 'Goedgekeurd',
    pl: 'Zatwierdzone',
    ru: 'Одобрено',
    sv: 'Godkänd',
    hr: 'Odobreno',
  },
  pending: {
    en: 'Pending',
    de: 'Ausstehend',
    fr: 'En attente',
    es: 'Pendiente',
    it: 'In attesa',
    pt: 'Pendente',
    nl: 'In afwachting',
    pl: 'Oczekujące',
    ru: 'На рассмотрении',
    sv: 'Väntande',
    hr: 'Na čekanju',
  },
  worldScore: {
    en: 'World Score',
    de: 'Weltweit',
    fr: 'Score mondial',
    es: 'Puntuación mundial',
    it: 'Punteggio mondiale',
    pt: 'Pontuação mundial',
    nl: 'Wereldscore',
    pl: 'Wynik światowy',
    ru: 'Мировой рейтинг',
    sv: 'Världspoäng',
    hr: 'Svjetska ocjena',
  },
  myLove: {
    en: 'My Love',
    de: 'Meine Liebe',
    fr: 'Mon amour',
    es: 'Mi amor',
    it: 'Il mio amore',
    pt: 'Meu amor',
    nl: 'Mijn liefde',
    pl: 'Moja miłość',
    ru: 'Моя любовь',
    sv: 'Min kärlek',
    hr: 'Moja ljubav',
  },
  editBook: {
    en: 'Edit Book',
    de: 'Buch bearbeiten',
    fr: 'Modifier le livre',
    es: 'Editar libro',
    it: 'Modifica libro',
    pt: 'Editar livro',
    nl: 'Boek bewerken',
    pl: 'Edytuj książkę',
    ru: 'Редактировать книгу',
    sv: 'Redigera bok',
    hr: 'Uredi knjigu',
  },
  signOut: {
    en: 'Sign Out',
    de: 'Abmelden',
    fr: 'Déconnexion',
    es: 'Cerrar sesión',
    it: 'Disconnetti',
    pt: 'Sair',
    nl: 'Uitloggen',
    pl: 'Wyloguj',
    ru: 'Выйти',
    sv: 'Logga ut',
    hr: 'Odjava',
  },
  noFlowers: {
    en: 'No flowers yet...',
    de: 'Noch keine Blumen...',
    fr: 'Pas encore de fleurs...',
    es: 'Aún no hay flores...',
    it: 'Ancora nessun fiore...',
    pt: 'Ainda não há flores...',
    nl: 'Nog geen bloemen...',
    pl: 'Jeszcze nie ma kwiatów...',
    ru: 'Пока нет цветов...',
    sv: 'Inga blommor ännu...',
    hr: 'Još nema cvijeća...',
  },
  safeInCloud: {
    en: 'Safe in the cloud',
    de: 'Sicher in der Cloud',
    fr: 'En sécurité dans le cloud',
    es: 'Seguro en la nube',
    it: 'Al sicuro nel cloud',
    pt: 'Seguro na nuvem',
    nl: 'Veilig in de cloud',
    pl: 'Bezpieczne w chmurze',
    ru: 'Безопасно в облаке',
    sv: 'Säkert i molnet',
    hr: 'Sigurno u oblaku',
  },
  cloudSync: {
    en: 'Cloud Sync Active',
    de: 'Cloud-Sync aktiv',
    fr: 'Synchronisation cloud active',
    es: 'Sincronización en la nube activa',
    it: 'Sincronizzazione cloud attiva',
    pt: 'Sincronização em nuvem ativa',
    nl: 'Cloud-sync actief',
    pl: 'Synchronizacja chmurowa aktywna',
    ru: 'Облачная синхронизация активна',
    sv: 'Molnsynkronisering aktiv',
    hr: 'Sinkronizacija u oblaku aktivna',
  },
  keeper: {
    en: 'Keeper',
    de: 'Hüter',
    fr: 'Gardien',
    es: 'Guardián',
    it: 'Custode',
    pt: 'Guardião',
    nl: 'Hoeder',
    pl: 'Opiekun',
    ru: 'Хранитель',
    sv: 'Vakt',
    hr: 'Čuvar',
  },
  explorer: {
    en: 'Explorer',
    de: 'Entdecker',
    fr: 'Explorateur',
    es: 'Explorador',
    it: 'Esploratore',
    pt: 'Explorador',
    nl: 'Ontdekker',
    pl: 'Odkrywca',
    ru: 'Исследователь',
    sv: 'Utforskare',
    hr: 'Istraživač',
  },
  local: {
    en: 'Local',
    de: 'Lokal',
    fr: 'Local',
    es: 'Local',
    it: 'Locale',
    pt: 'Local',
    nl: 'Lokaal',
    pl: 'Lokalne',
    ru: 'Локально',
    sv: 'Lokal',
    hr: 'Lokalno',
  },
  leaveGarden: {
    en: 'Leave garden?',
    de: 'Garten verlassen?',
    fr: 'Quitter le jardin ?',
    es: '¿Salir del jardín?',
    it: 'Lasciare il giardino?',
    pt: 'Sair do jardim?',
    nl: 'Tuin verlaten?',
    pl: 'Opuścić ogród?',
    ru: 'Покинуть сад?',
    sv: 'Lämna trädgården?',
    hr: 'Napustiti vrt?',
  },
  yesGoBack: {
    en: 'Yes, Go Back',
    de: 'Ja, zurück',
    fr: 'Oui, revenir',
    es: 'Sí, Volver',
    it: 'Sì, Torna indietro',
    pt: 'Sim, Voltar',
    nl: 'Ja, Terug',
    pl: 'Tak, Wróć',
    ru: 'Да, назад',
    sv: 'Ja, Gå tillbaka',
    hr: 'Da, Vrati se',
  },
  keepReading: {
    en: 'Keep Reading',
    de: 'Weiter lesen',
    fr: 'Continuer la lecture',
    es: 'Seguir leyendo',
    it: 'Continua a leggere',
    pt: 'Continuar lendo',
    nl: 'Blijf lezen',
    pl: 'Kontynuuj czytanie',
    ru: 'Продолжить чтение',
    sv: 'Fortsätt läsa',
    hr: 'Nastavi čitati',
  },
};
